;;; Copyright 2020 Metaphorm Solutions, Inc.
;;;
;;; Licensed under the Apache License, Version 2.0 (the "License");
;;; you may not use this file except in compliance with the License.
;;; You may obtain a copy of the License at
;;;
;;; http://www.apache.org/licenses/LICENSE-2.0
;;;
;;; Unless required by applicable law or agreed to in writing, software
;;; distributed under the License is distributed on an "AS IS" BASIS,
;;; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;;; See the License for the specific language governing permissions and
;;; limitations under the License.

;;; Scheme (R6RS) Translation Template
;;; Use this file as a starting point for translations to your language.
;;; Simply replace each todo with a translation of the identifier to its left.

(load "international.scm")

(translate-syntax-names
  and todo
  assert todo
  begin todo
  buffer-mode todo
  buffer-mode? todo
  case todo (else todo)
  case-lambda todo
  cond todo (else todo)
  define todo
  define-condition-type todo
  define-enumeration todo
  define-record-type todo (fields todo
                           mutable todo
                           immutable todo
                           parent todo
                           protocol todo
                           sealed todo
                           opaque todo
                           nongenerative todo
                           parent-rtd todo)
  define-syntax todo
  delay todo
  do todo
  endianness todo
  eol-style todo
  error-handling-mode todo
  file-options todo
  guard todo (else todo)
  identifier-syntax todo
  if todo
  lambda todo
  let todo
  let* todo
  let*-values todo
  let-syntax todo
  let-values todo
  letrec todo
  letrec* todo
  letrec-syntax todo
  library todo (and todo
                or todo
                not todo
                import todo
                for todo
                run todo
                expand todo
                meta todo
                only todo
                except todo
                prefix todo
                rename todo
                export todo
                rename todo)
  or todo
  quasiquote todo (unquote todo
                   unquote-splicing todo)
  quasisyntax todo
  quote todo
  record-constructor-descriptor todo
  record-type-descriptor todo
  set! todo
  syntax todo
  syntax-case todo
  syntax-rules todo
  unless todo
  unsyntax todo
  unsyntax-splicing todo
  when todo
  with-syntax todo)

(translate-procedure-names
  * todo
  + todo
  - todo
  / todo
  < todo
  <= todo
  = todo
  > todo
  >= todo
  abs todo
  acos todo
  angle todo
  append todo
  apply todo
  asin todo
  assertion-violation todo
  assertion-violation? todo
  assoc todo
  assp todo
  assq todo
  assv todo
  atan todo
  binary-port? todo
  bitwise-and todo
  bitwise-arithmetic-shift todo
  bitwise-arithmetic-shift-left todo
  bitwise-arithmetic-shift-right todo
  bitwise-bit-count todo
  bitwise-bit-field todo
  bitwise-bit-set? todo
  bitwise-copy-bit todo
  bitwise-copy-bit-field todo
  bitwise-first-bit-set todo
  bitwise-if todo
  bitwise-ior todo
  bitwise-length todo
  bitwise-not todo
  bitwise-reverse-bit-field todo
  bitwise-rotate-bit-field todo
  bitwise-xor todo
  boolean=? todo
  boolean? todo
  bound-identifier=? todo
  bytevector->sint-list todo
  bytevector->string todo
  bytevector->u8-list todo
  bytevector->uint-list todo
  bytevector-copy todo
  bytevector-copy! todo
  bytevector-fill! todo
  bytevector-ieee-double-native-ref todo
  bytevector-ieee-double-native-set! todo
  bytevector-ieee-double-ref todo
  bytevector-ieee-double-set! todo
  bytevector-ieee-single-native-ref todo
  bytevector-ieee-single-native-set! todo
  bytevector-ieee-single-ref todo
  bytevector-ieee-single-set! todo
  bytevector-length todo
  bytevector-s16-native-ref todo
  bytevector-s16-native-set! todo
  bytevector-s16-ref todo
  bytevector-s16-set! todo
  bytevector-s32-native-ref todo
  bytevector-s32-native-set! todo
  bytevector-s32-ref todo
  bytevector-s32-set! todo
  bytevector-s64-native-ref todo
  bytevector-s64-native-set! todo
  bytevector-s64-ref todo
  bytevector-s64-set! todo
  bytevector-s8-ref todo
  bytevector-s8-set! todo
  bytevector-sint-ref todo
  bytevector-sint-set! todo
  bytevector-u16-native-ref todo
  bytevector-u16-native-set! todo
  bytevector-u16-ref todo
  bytevector-u16-set! todo
  bytevector-u32-native-ref todo
  bytevector-u32-native-set! todo
  bytevector-u32-ref todo
  bytevector-u32-set! todo
  bytevector-u64-native-ref todo
  bytevector-u64-native-set! todo
  bytevector-u64-ref todo
  bytevector-u64-set! todo
  bytevector-u8-ref todo
  bytevector-u8-set! todo
  bytevector-uint-ref todo
  bytevector-uint-set! todo
  bytevector=? todo
  bytevector? todo
  caaaar todo
  caaadr todo
  caaar todo
  caadar todo
  caaddr todo
  caadr todo
  caar todo
  cadaar todo
  cadadr todo
  cadar todo
  caddar todo
  cadddr todo
  caddr todo
  cadr todo
  call-with-bytevector-output-port todo
  call-with-current-continuation todo
  call-with-input-file todo
  call-with-output-file todo
  call-with-port todo
  call-with-string-output-port todo
  call-with-values todo
  call/cc todo
  car todo
  cdaaar todo
  cdaadr todo
  cdaar todo
  cdadar todo
  cdaddr todo
  cdadr todo
  cdar todo
  cddaar todo
  cddadr todo
  cddar todo
  cdddar todo
  cddddr todo
  cdddr todo
  cddr todo
  cdr todo
  ceiling todo
  char->integer todo
  char-alphabetic? todo
  char-ci<=? todo
  char-ci<? todo
  char-ci=? todo
  char-ci>=? todo
  char-ci>? todo
  char-downcase todo
  char-foldcase todo
  char-general-category todo
  char-lower-case? todo
  char-numeric? todo
  char-title-case? todo
  char-titlecase todo
  char-upcase todo
  char-upper-case? todo
  char-whitespace? todo
  char<=? todo
  char<? todo
  char=? todo
  char>=? todo
  char>? todo
  char? todo
  close-input-port todo
  close-output-port todo
  close-port todo
  command-line todo
  complex? todo
  condition todo
  condition-accessor todo
  condition-irritants todo
  condition-message todo
  condition-predicate todo
  condition-who todo
  condition? todo
  cons todo
  cons* todo
  cos todo
  current-error-port todo
  current-input-port todo
  current-output-port todo
  datum->syntax todo
  delete-file todo
  denominator todo
  display todo
  div todo
  div-and-mod todo
  div0 todo
  div0-and-mod0 todo
  dynamic-wind todo
  enum-set->list todo
  enum-set-complement todo
  enum-set-constructor todo
  enum-set-difference todo
  enum-set-indexer todo
  enum-set-intersection todo
  enum-set-member? todo
  enum-set-projection todo
  enum-set-subset? todo
  enum-set-union todo
  enum-set-universe todo
  enum-set=? todo
  environment todo
  eof-object todo
  eof-object? todo
  eq? todo
  equal-hash todo
  equal? todo
  eqv? todo
  error todo
  error? todo
  eval todo
  even? todo
  exact todo
  exact->inexact todo
  exact-integer-sqrt todo
  exact? todo
  exists todo
  exit todo
  exp todo
  expt todo
  file-exists? todo
  filter todo
  find todo
  finite? todo
  fixnum->flonum todo
  fixnum-width todo
  fixnum? todo
  fl* todo
  fl+ todo
  fl- todo
  fl/ todo
  fl<=? todo
  fl<? todo
  fl=? todo
  fl>=? todo
  fl>? todo
  flabs todo
  flacos todo
  flasin todo
  flatan todo
  flceiling todo
  flcos todo
  fldenominator todo
  fldiv todo
  fldiv-and-mod todo
  fldiv0 todo
  fldiv0-and-mod0 todo
  fleven? todo
  flexp todo
  flexpt todo
  flfinite? todo
  flfloor todo
  flinfinite? todo
  flinteger? todo
  fllog todo
  flmax todo
  flmin todo
  flmod todo
  flmod0 todo
  flnan? todo
  flnegative? todo
  flnumerator todo
  flodd? todo
  flonum? todo
  floor todo
  flpositive? todo
  flround todo
  flsin todo
  flsqrt todo
  fltan todo
  fltruncate todo
  flush-output-port todo
  flzero? todo
  fold-left todo
  fold-right todo
  for-all todo
  for-each todo
  force todo
  free-identifier=? todo
  fx* todo
  fx*/carry todo
  fx+ todo
  fx+/carry todo
  fx- todo
  fx-/carry todo
  fx<=? todo
  fx<? todo
  fx=? todo
  fx>=? todo
  fx>? todo
  fxand todo
  fxarithmetic-shift todo
  fxarithmetic-shift-left todo
  fxarithmetic-shift-right todo
  fxbit-count todo
  fxbit-field todo
  fxbit-set? todo
  fxcopy-bit todo
  fxcopy-bit-field todo
  fxdiv todo
  fxdiv-and-mod todo
  fxdiv0 todo
  fxdiv0-and-mod0 todo
  fxeven? todo
  fxfirst-bit-set todo
  fxif todo
  fxior todo
  fxlength todo
  fxmax todo
  fxmin todo
  fxmod todo
  fxmod0 todo
  fxnegative? todo
  fxnot todo
  fxodd? todo
  fxpositive? todo
  fxreverse-bit-field todo
  fxrotate-bit-field todo
  fxxor todo
  fxzero? todo
  gcd todo
  generate-temporaries todo
  get-bytevector-all todo
  get-bytevector-n todo
  get-bytevector-n! todo
  get-bytevector-some todo
  get-char todo
  get-datum todo
  get-line todo
  get-string-all todo
  get-string-n todo
  get-string-n! todo
  get-u8 todo
  greatest-fixnum todo
  hashtable-clear! todo
  hashtable-contains? todo
  hashtable-copy todo
  hashtable-delete! todo
  hashtable-entries todo
  hashtable-equivalence-function todo
  hashtable-hash-function todo
  hashtable-keys todo
  hashtable-mutable? todo
  hashtable-ref todo
  hashtable-set! todo
  hashtable-size todo
  hashtable-update! todo
  hashtable? todo
  i/o-decoding-error? todo
  i/o-encoding-error-char todo
  i/o-encoding-error? todo
  i/o-error-filename todo
  i/o-error-port todo
  i/o-error-position todo
  i/o-error? todo
  i/o-file-already-exists-error? todo
  i/o-file-does-not-exist-error? todo
  i/o-file-is-read-only-error? todo
  i/o-file-protection-error? todo
  i/o-filename-error? todo
  i/o-invalid-position-error? todo
  i/o-port-error? todo
  i/o-read-error? todo
  i/o-write-error? todo
  identifier? todo
  imag-part todo
  implementation-restriction-violation? todo
  inexact todo
  inexact->exact todo
  inexact? todo
  infinite? todo
  input-port? todo
  integer->char todo
  integer-valued? todo
  integer? todo
  irritants-condition? todo
  latin-1-codec todo
  lcm todo
  least-fixnum todo
  length todo
  lexical-violation? todo
  list todo
  list->string todo
  list->vector todo
  list-ref todo
  list-sort todo
  list-tail todo
  list? todo
  load todo
  log todo
  lookahead-char todo
  lookahead-u8 todo
  magnitude todo
  make-assertion-violation todo
  make-bytevector todo
  make-custom-binary-input-port todo
  make-custom-binary-input/output-port todo
  make-custom-binary-output-port todo
  make-custom-textual-input-port todo
  make-custom-textual-input/output-port todo
  make-custom-textual-output-port todo
  make-enumeration todo
  make-eq-hashtable todo
  make-eqv-hashtable todo
  make-error todo
  make-hashtable todo
  make-i/o-decoding-error todo
  make-i/o-encoding-error todo
  make-i/o-error todo
  make-i/o-file-already-exists-error todo
  make-i/o-file-does-not-exist-error todo
  make-i/o-file-is-read-only-error todo
  make-i/o-file-protection-error todo
  make-i/o-filename-error todo
  make-i/o-invalid-position-error todo
  make-i/o-port-error todo
  make-i/o-read-error todo
  make-i/o-write-error todo
  make-implementation-restriction-violation todo
  make-irritants-condition todo
  make-lexical-violation todo
  make-message-condition todo
  make-no-infinities-violation todo
  make-no-nans-violation todo
  make-non-continuable-violation todo
  make-polar todo
  make-record-constructor-descriptor todo
  make-record-type-descriptor todo
  make-rectangular todo
  make-serious-condition todo
  make-string todo
  make-syntax-violation todo
  make-transcoder todo
  make-undefined-violation todo
  make-variable-transformer todo
  make-vector todo
  make-violation todo
  make-warning todo
  make-who-condition todo
  map todo
  max todo
  member todo
  memp todo
  memq todo
  memv todo
  message-condition? todo
  min todo
  mod todo
  mod0 todo
  modulo todo
  nan? todo
  native-endianness todo
  native-eol-style todo
  native-transcoder todo
  negative? todo
  newline todo
  no-infinities-violation? todo
  no-nans-violation? todo
  non-continuable-violation? todo
  not todo
  null-environment todo
  null? todo
  number->string todo
  number? todo
  numerator todo
  odd? todo
  open-bytevector-input-port todo
  open-bytevector-output-port todo
  open-file-input-port todo
  open-file-input/output-port todo
  open-file-output-port todo
  open-input-file todo
  open-output-file todo
  open-string-input-port todo
  open-string-output-port todo
  output-port-buffer-mode todo
  output-port? todo
  pair? todo
  partition todo
  peek-char todo
  port-eof? todo
  port-has-port-position? todo
  port-has-set-port-position!? todo
  port-position todo
  port-transcoder todo
  port? todo
  positive? todo
  procedure? todo
  put-bytevector todo
  put-char todo
  put-datum todo
  put-string todo
  put-u8 todo
  quotient todo
  raise todo
  raise-continuable todo
  rational-valued? todo
  rational? todo
  rationalize todo
  read todo
  read-char todo
  real->flonum todo
  real-part todo
  real-valued? todo
  real? todo
  record-accessor todo
  record-constructor todo
  record-field-mutable? todo
  record-mutator todo
  record-predicate todo
  record-rtd todo
  record-type-descriptor? todo
  record-type-field-names todo
  record-type-generative? todo
  record-type-name todo
  record-type-opaque? todo
  record-type-parent todo
  record-type-sealed? todo
  record-type-uid todo
  record? todo
  remainder todo
  remove todo
  remp todo
  remq todo
  remv todo
  reverse todo
  round todo
  scheme-report-environment todo
  serious-condition? todo
  set-car! todo
  set-cdr! todo
  set-port-position! todo
  simple-conditions todo
  sin todo
  sint-list->bytevector todo
  sqrt todo
  standard-error-port todo
  standard-input-port todo
  standard-output-port todo
  string todo
  string->bytevector todo
  string->list todo
  string->number todo
  string->symbol todo
  string->utf16 todo
  string->utf32 todo
  string->utf8 todo
  string-append todo
  string-ci-hash todo
  string-ci<=? todo
  string-ci<? todo
  string-ci=? todo
  string-ci>=? todo
  string-ci>? todo
  string-copy todo
  string-downcase todo
  string-fill! todo
  string-foldcase todo
  string-for-each todo
  string-hash todo
  string-length todo
  string-normalize-nfc todo
  string-normalize-nfd todo
  string-normalize-nfkc todo
  string-normalize-nfkd todo
  string-ref todo
  string-set! todo
  string-titlecase todo
  string-upcase todo
  string<=? todo
  string<? todo
  string=? todo
  string>=? todo
  string>? todo
  string? todo
  substring todo
  symbol->string todo
  symbol-hash todo
  symbol=? todo
  symbol? todo
  syntax->datum todo
  syntax-violation todo
  syntax-violation-form todo
  syntax-violation-subform todo
  syntax-violation? todo
  tan todo
  textual-port? todo
  transcoded-port todo
  transcoder-codec todo
  transcoder-eol-style todo
  transcoder-error-handling-mode todo
  truncate todo
  u8-list->bytevector todo
  uint-list->bytevector todo
  undefined-violation? todo
  utf-16-codec todo
  utf-8-codec todo
  utf16->string todo
  utf32->string todo
  utf8->string todo
  values todo
  vector todo
  vector->list todo
  vector-fill! todo
  vector-for-each todo
  vector-length todo
  vector-map todo
  vector-ref todo
  vector-set! todo
  vector-sort todo
  vector-sort! todo
  vector? todo
  violation? todo
  warning? todo
  who-condition? todo
  with-exception-handler todo
  with-input-from-file todo
  with-output-to-file todo
  write todo
  write-char todo
  zero? todo)
